### PR TITLE
Fix/frontend errors

### PR DESCRIPTION
**Pull request by samar12-rad**
Description:
@ayerhssb , This PR addresses multiple frontend errors in the café website project and enhances the API integration, enabling seamless registration and login for both doctors and patients.

Changes Made:

Fixed useState ReferenceError:
Corrected the import statement for useState in Doctors.jsx, ensuring the hook is properly imported from React.

Resolved JSON Stringify ReferenceError:
Fixed the incorrect usage of JSON.stringify in AuthContext.jsx, ensuring it is called correctly.

Improved API Calls:
Updated API calls to ensure they work seamlessly with the frontend and backend.
Verified that doctors and patients can now register and log in without issues.

Added useEffect Hook:
Integrated the useEffect hook where necessary to handle side effects and improve component lifecycle management.

Implemented Props Validation:
Added prop validation using PropTypes to ensure that components receive the correct types of props, enhancing code reliability and maintainability.

General Code Consistency:
Reviewed the codebase for other inconsistencies and errors, correcting any instances that could lead to runtime issues.

### CODE REVIEW

**Comment by samar12-rad** [comment]
@ayerhssb , this was for issue #2

**Comment by samar12-rad** [comment]
@ayerhssb Can you provide me lables for this work?

**Comment by samar12-rad** [comment]
@sanjay-kv , no response from admin

**Comment by sanjay-kv** [comment]
@samar12-rad give some time, usually it take 3 to 4 times to get response on the opensource projects. try other projects as well.

**Comment by samar12-rad** [comment]
Ok

**Comment by samar12-rad** [comment]
for issue #2

**Comment by samar12-rad** [comment]
@ayerhssb , can you assign labels  to this, i made the code running fixing proper frontend and backend integrations.

**Comment by samar12-rad** [comment]
@sanjay-kv, i have not been assigned labels on this pr.

**Pull request merged**
